FROM mcr.microsoft.com/devcontainers/base:alpine-3.19
RUN apk add --update --no-cache \
    --repository https://dl-cdn.alpinelinux.org/alpine/latest-stable/community \
    go>=1.21.8-r0 php83>=8.3.4-r0
